spring:
  datasource:
    url: jdbc:mysql://database-1.cf2cmrhaysfc.us-west-1.rds.amazonaws.com:3306/blog
    username: admin
    password: Amazon1004!
  jpa.show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: redis-15612.c60.us-west-1-2.ec2.cloud.redislabs.com
    port: 15612
    password: vBzXEtRzRORNbyThiVf3tppqCdzcwcn2
logging.level.org.springframework: info
server.port: 5000
