spring:
  datasource:
    url: jdbc:mysql://database-1.cf2cmrhaysfc.us-west-1.rds.amazonaws.com:3306/blog
    username: admin
    password: Amazon1004!
  jpa.show-sql: true
logging.level.org.springframework: info
server.port: 5000
