###
GET http://localhost:5000/

###
GET http://localhost:5000/categories

###
GET http://localhost:5000/posts

###
GET http://localhost:5000/posts?categoryId=1

###
GET http://localhost:5000/headlines
